services:
  postgres:
    image: postgres
    volumes:
       - postgres:/data/postgres
    #ports:
      #- "5432:5432"
    #networks:
      #- postgres
    restart: unless-stopped
    # set max_connections to small number to test effect of max_connections
    # reference: https://stackoverflow.com/a/54484269
    command: postgres -c 'max_connections=20'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      PGDATA: /data/postgres

  web_serve:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    #volumes:
      #- .:/srv/laravel
    command: php artisan serve --host 0.0.0.0 --port 8000

  web_octane_roadrunner:
    build:
      context: .
    ports:
      #- 8001:8000
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
    scale: 5

  # use nginx as load balancer & reverse proxy
  # ref: https://medium.com/@vinodkrane/microservices-scaling-and-load-balancing-using-docker-compose-78bf8dc04da9
  load_balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web_octane_roadrunner
      - web_serve
    ports:
      - 8888:8888

volumes:
    postgres:
