services:
  web_serve:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    #volumes:
      #- .:/srv/laravel
    command: php artisan serve --host 0.0.0.0 --port 8000

  web_octane_roadrunner:
    build:
      context: .
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
       - postgres:/data/postgres
    #ports:
      #- "5432:5432"
    #networks:
      #- postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      PGDATA: /data/postgres

#networks:
  #postgres:
    #driver: bridge

volumes:
    postgres:
